---
title: "APSTA-GE 2006 Fall 2025"
subtitle: "Statistics, Math, and Computing Bootcamp"
author: "Instructor: eric.novik@nyu.edu"
date: today
date-format: "D MMM YYYY"
format:
  pdf:
    documentclass: scrartcl
    papersize: letter
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    toc: false
    number-sections: true
    colorlinks: true
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course description

This course aims to prepare students for the [Applied Statistics for Social Science Research](https://steinhardt.nyu.edu/degree/ms-applied-statistics-social-science-research) or an equivalent program at NYU. We will cover basic programming using the R language, including data manipulation and graphical displays; some key ideas from Calculus, including differentiation and integration, basic matrix algebra, including vector and matrix arithmetic; some core concepts in Probability, including random variables, discrete and continuous distributions, and expectations; and a few simple regression examples. We will also discuss the use of modern AI and LLMs in computational statistics.

## Where and when

The course will run from August 18 through August 29. We will meet on weekdays from 9 a.m. to 12 p.m. at 7 East 12th Street, Room 329, and for those who can't attend in person on Zoom. Students are strongly encouraged to attend in person, as this course will be highly interactive.

## Course prerequisites

The students should be fluent in basic algebra and have seen exponential and logarithmic functions. Some programming experience would be helpful but not required. Students should be prepared to write many small R programs during the course.

## Course materials and references

Students are expected to have access to R and RStudio. Use [these](https://rstudio-education.github.io/hopr/starting.html) instructions on downloading and installing the required software. In addition, you may find the following free resources helpful as you continue your studies.

### Programming and Data Visualization

-   [Hands-On Programming with R](https://rstudio-education.github.io/hopr/), @grolemund2014

-   [R for Data Science](https://r4ds.hadley.nz/), @wickham2023

-   [Data Visualization, A practical introduction](https://socviz.co/), @healy2018

### Calculus

-   [YouTube: Essence of Calculus](https://bit.ly/calc-3blue1brown), @sanderson2018

-   [Calculus Made Easy](http://calculusmadeeasy.org/), @thompson1980

-   [Calculus](https://openstax.org/details/books/calculus-volume-1), @herman2016

### Probability

-   [YouTube: Probability Animations](https://www.youtube.com/playlist?list=PLltdM60MtzxNwhL4sg7swFFlUlH7EEy7H)

-   [YouTube: Statistics 110 \@ Harvard](https://www.youtube.com/playlist?list=PL2SOU6wwxB0uwwH80KTQ6ht66KWxbzTIo)

-   [Introduction to Probability](https://projects.iq.harvard.edu/stat110/home), @blitzstein2019

-   [Introduction to Probability Cheat sheet v2](https://static1.squarespace.com/static/54bf3241e4b0f0d81bf7ff36/t/55e9494fe4b011aed10e48e5/1441352015658/probability_cheatsheet.pdf), Chen (2015)

### Statistics

-   [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/), @Gelman2020-bv

### Linear Algebra (for those who need it)

-   [YouTube: Essense of Linear Algebra](https://bit.ly/lin-algebra-3blue1brown), @sanderson2018a

-   [Introduction to Linear Algebra](https://web.stanford.edu/~boyd/vmls/), @boyd2018

-   [Matrix Cookbook](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf), @petersen2012

## Tentative schedule

The following tentative schedule assumes ten 3-hour sessions, during which we plan to cover the following material.

-   **(1) The Big Picture and Introduction to R**

    We will briefly discuss the motivation behind the topics in the class and give some examples of the types of regression problems you may encounter. We will use Shuttle O-Rings damage and John Snow's (the other one) Cholera datasets as motivating examples. We will introduce programming principles in R, including RStudio IDE, R objects, built-in functions, and how to write your own functions.

    -   Hands-On Programming with R*, [Part 1](https://rstudio-education.github.io/hopr/project-1-weighted-dice.html).*
    -   R for Data Science, [Introduction](https://r4ds.hadley.nz/intro).
    -   YouTube: Essence of Calculus, Videos [1](https://youtu.be/WUvTyaaNkzM), [2](https://youtu.be/9vKqVkMQHKk), [3](https://youtu.be/S0_qX4VJhMQ).

-   **(2) Plotting, Exponentials, Logs, and Derivatives**

    We will review linear, exponential, and logarithmic functions and develop some intuition using compound interest. We will explain and code a softmax function using the log-sum-exp trick. Furthermore, we will introduce a derivative geometrically and symbolically. We will cover basic rules for differentiating functions and use noisy measurements of motion in a straight line as a motivating example. We will also practice plotting lines and curves using base `plot` and `ggplot2`.

    -   Hands-On Programming with R*, [Part 2](https://rstudio-education.github.io/hopr/project-2-playing-cards.html)*
    -   R for Data Science, [Data visualization](https://r4ds.hadley.nz/data-visualize)
    -   YouTube: Essence of Calculus, Videos [4](https://youtu.be/YG15m2VwSjA), [5](https://youtu.be/m2MIpDrF7Es), [6](https://youtu.be/qb40J4N1fa4).

-   **(3) Reshaping Data, Loops, and Maps; Introduction to Integration**

    We will practice data wrangling using `dplyr` and `tidyr` packages. We will cover the intuition behind integration, approximating areas, the definite integral, and review the basic integration rules. We will learn how to do numerical and symbolic integration (in one dimension) using R.

    -   Hands-On Programming with R*, [Part 3](https://rstudio-education.github.io/hopr/project-3-slot-machine.html).*
    -   R for Data Science, [Data transformations](https://r4ds.hadley.nz/data-transform).
    -   YouTube: Essence of Calculus, Videos [7](https://youtu.be/kfF40MiS7zA), [8](https://youtu.be/FnJqaIESC2s), [9](https://youtu.be/FnJqaIESC2s).

-   **(4) Introduction to Probability 1**

    We will review sample spaces, counting, and introduce the axiomatic definition of probability. We will discuss how to solve probability problems using simulations and will go through a few famous paradoxes. We will extensively use R's `sample` and `replicate` functions.

    -   R for Data Science, [Data Tidying](https://r4ds.hadley.nz/data-tidy)
    -   [Introduction to Probability](https://projects.iq.harvard.edu/stat110/home), Chapter 1
    -   YouTube: Essence of Calculus, Videos [10](https://youtu.be/BLkz5LGWihw), [11](https://youtu.be/3d6DsjIBzJ4), [12](https://youtu.be/CfW845LNObM).

-   **(5) Introduction to Probability 2**

    We will introduce conditional probability, the law of total probabilities, and independence and discuss a few famous paradoxes. We will write R simulations to check analytic solutions.

    -   [Introduction to Probability](https://projects.iq.harvard.edu/stat110/home), Chapter 2

-   **(6) Introduction to Probability 3**

    We will introduce Random Variables, PDFs, and CDFs. We will cover Bernoulli, Binomial, Uniform, Normal, and Exponential RVs. We will discuss the concept of expectations. We will use R's distribution functions to simulate the realizations of RVs and compute their properties.

    -   [Introduction to Probability](https://projects.iq.harvard.edu/stat110/home), Chapter 3

-   **(7) Introduction to Linear Algebra**

    We will review the basics of Linear Algebra, including vector and matrix addition and multiplication. We will practice matrix and vector arithmetic in R. Time permitting, we will solve the over-determined system of linear equations for the motion in a straight-line problem from Lecture 2.

    -   YouTube: Essence of Linear Algebra, Videos [1](https://youtu.be/fNk_zzaMoSs), [2](https://youtu.be/k7RM-ot2NWY), [3](https://youtu.be/kYB8IZa5AuE)

-   **(8) Statistical Inference**

    We will cover basic topics in Statistical Inference including sampling distributions, standard errors, classical confidence intervals, bias and uncertainty, and problems associated with unconscious use of statistical significance for making decisions.

    -   Regression and Other Stories, [Chapter 4](https://avehtari.github.io/ROS-Examples/)

-   **(9) Analysis Workflow and Linear Regression**

    We will introduce an analysis workflow using a dataset containing ratings of red wines. We will use the `rstanarm` package, but the same model can be done in with R's `lm()` function. We will attempt to determine what makes a good wine. After doing some basic EDA, we will fit several regressions and evaluate how well our model performs.

    -   [Introduction to Probability](https://projects.iq.harvard.edu/stat110/home), Chapter 3

-   **(10) Review and Discussion**

    This is a buffer lecture where we will cover the overflow topics from the previous days. Time permitting, we will also quickly review the material, answer questions, and discuss the contents of the final assessment.

## Assessment

This is a Pass/Fail class with the following grade distribution.

-   Class participation: 50%
-   Final assessment (take home): 50%

To earn class participation credit, students must attend all lectures *and* post in the online lecture discussions on Brightspace under the Online Discussion topic. For each lecture, please ask a question about the material, respond to a question asked by another student, or post an observation.

The final assessment will consist of approximately ten questions covering all major topics in the class. The final will be distributed during the last day of class.

## Academic Integrity

All students are responsible for understanding and complying with the [NYU Steinhardt Policies and Academic Integrity](https://steinhardt.nyu.edu/current-students/academic-policies-and-procedures).

## Students with Disabilities Statement

Students with physical or learning disabilities are required to register with the Moses Center for Students with Disabilities at 726 Broadway, 2nd Floor, (212-998-4980) and are required to present a letter from the Center to the instructor at the start of the semester in order to be considered for appropriate accommodation.

## Mental Health Statement

If you are experiencing undue personal and/or academic stress during the semester that may be interfering with your ability to perform academically, the NYU Wellness Exchange (212 443 9999) offers a range of services to assist and support you. I am available to speak with you about stresses related to your work in my course, and I can assist you in connecting with the Wellness Exchange. Additionally, if you anticipate any challenges with completing the assignments, readings, exams and other work required in this course, I encourage you to register with the Moses Center (212 998 4980) in advance so that you may be granted the proper academic accommodations.

## References
