project:
  type: website
  render:
    - "*.qmd"
    #- "bayes-course/"
    - "stats-math/"

clean: false

website:
  title: "Eric Novik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - smac.qmd
      - bayes-course.qmd
      
format:
  revealjs: 
    theme: custom.scss
    scrollable: true
    slide-number: true
    chalkboard: 
      buttons: false
      chalk-width: 5
    preview-links: auto

execute:
  freeze: auto
  
editor: visual

