project:
  type: website

website:
  title: "Eric Novik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - bayes-course.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

