project:
  type: website

website:
  title: "Eric Novik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - bayes-course.qmd

format:
  revealjs: 
    theme: custom.scss
    scrollable: true
    slide-number: true
    chalkboard: 
      buttons: false
      chalk-width: 5
    preview-links: auto

editor: visual

