---
title: "Bayesian Workflow"
subtitle: "Applied Statistics for Social Science Research"
author: "Eric Novik | Spring 2023 | Lecture 1"
format:
  revealjs: 
    theme: [serif, custom]
    scrollable: true
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    footer: <https://steinhardt.nyu.edu/>
editor: source
always_allow_html: true
---

## Lecture 1

::: incremental
-   Statistics vs AI/ML
-   Brief history of Bayesian inference
-   Introduction to Bayesian workflow
-   Deconstructing the Bayes rule
:::

```{r}
library(ggplot2)
thm <-
  theme_minimal() + theme(
    panel.background = element_rect(fill = "#f0f1eb", color = "#f0f1eb"),
    plot.background = element_rect(fill = "#f0f1eb", color = "#f0f1eb")
  )
theme_set(thm)
```

## Statistics vs AI/ML {.smaller}

⚠️This is an oversimplified opinion.

::: columns
::: {.column width="50%"}
::: incremental
-   AI is great for automating tasks that humans find easy
    -   Driving a car
    -   Recognizing faces, cats, and other objects
    -   Identifying tumors on a radiology scan
:::
:::

::: {.column width="50%"}
::: incremental
-   Statistics is great at answering questions that humans find hard
    -   How fast does a drug clear from the body?
    -   What is the expected tumor size in 2 months after treatment?
    -   How would patients respond under a different treatment?
    -   Should I take this drug?
:::
:::
:::

## Brief History
- Thomas Bayes (1702 --- 1761) was an English clergyman
- 

## Statistical Models and Inferences

-   A model is our description of the small world that generablly contains:
    -   A model for the conditional mean like $X\beta$ or a differential equation describing a dynamical system
    -   A likelihood term that contains the mean, nois
    -   A prior model for the unkowns
